server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://127.0.0.1:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
          - Path=/api/v1/customers/save/**
#        - id: customer
#          uri: lb://FRAUD
#          predicates:
#            - Path=api/v1/fraud-check/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/